server:
  port: 8102

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #true表示将本微服务（我/微服务的提供者）注册到eureka服务端，默认为true
    fetch-registry: true #true表示从eureka服务端抓取已被注册的微服务，默认为true
    #注意，单节点eureka服务端是无所谓的，eureka服务端集群必须设置为true才能配合ribbon使用负载均衡机制
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka 将本微服务（我）注册到eureka服务端的具体地址（单节点eureka服务端）
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #eureka服务端集群
  instance:
    instance-id: ${spring.cloud.client.hostname}:order:${server.port}:${spring.application.name} #微服务实例标识（几号机、几号端口、什么微服务）
    prefer-ip-address: true #访问路径可以显示ip地址
