server:
  port: 8106

spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      host: localhost # 45.77.99.153
      port: 8500
      discovery:
        service-name: ${spring.application.name}
