server:
  port: 8107

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: localhost # 45.77.99.153
      port: 8500
      discovery:
        service-name: ${spring.application.name}
