server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心（eureka服务端）注册自己（eureka服务端）
                                #false表示本微服务（我）就是注册中心，我的职责就是维护服务实例
    fetch-registry: false
    service-url:
      #与eureka服务端交互的地址查询服务和注册服务，都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  server:
    enable-self-preservation: true #关闭eureka服务端的自我保护机制（默认为true表示eureka服务端的自我保护机制默认是开启的），即一定时间内（默认90秒）没有接收到eureka客户端发送的心跳包，立马剔除掉它
    eviction-interval-timer-in-ms: 10000 #将默认90秒的时间间隔改成10秒
