server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心（eureka服务端）注册自己（eureka服务端）
                                #false表示本微服务（我）就是注册中心，我的职责就是维护服务实例
    fetch-registry: false
    service-url:
      #与eureka服务端交互的地址查询服务和注册服务，都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
